### ISSUE TITLE
NUnit 3 is not supported

### ISSUE THREAD

**Issue by yury-staravoitau-epam** [allure-framework/allure-nunit2#20]
In the current moment, nunit 3 is release. 3.2 is current version.

Could you please add NUnit support?

**Comment by ilya-murzinov** [comment]
Hey!
I have no plans to add support for NUnit3 because I don't have time for it.
Hope that community will do it some day.

**Comment by sergmal** [comment]
no news? :(

**Comment by Bakanych** [comment]
Hi @sergmal,
you can check this approach so far: https://github.com/unickq/allure-nunit

**Comment by sergmal** [comment]
Thanks for reply Bakanych.
Do you know if the Step attribute will work as well? I used this feature in Java but really miss it in c#

"In order to define steps in Java code, you need to annotate the respective methods with @Step annotation. **When not specified, the step name is equal to the annotated method name converted to human-readable format**."
https://docs.qameta.io/allure/latest/

**Comment by unickq** [comment]
https://github.com/unickq/allure-nunit
